language: python

matrix:
  include:
    - os: linux
      python: 3.6
      dist: trusty
    - os: linux
      python: 3.7
      dist: xenial

install:
  - tools/travis-install.sh

script:
  - tools/run-test.sh
